### ISSUE TITLE
Setting Debug = true causes BranchException. You must initialize Branch before...

### ISSUE THREAD

**Issue by maqui01** [BranchMetrics/xamarin-branch-deep-linking#14]
Hi guys,

I'm triying to simulate Installs on the Xamarin App and It fails.

I'm following this guide: https://dev.branch.io/getting-started/integration-testing/guide/xamarin/#use-debug-mode-to-simulate-fresh-installs

```
BranchAndroid.GetInstance().Debug = true;
BranchAndroid.Init (this, "key_live_xxxxxxxxxxxxxx", Intent.Data, Intent.Extras);
// Call this method to enable automatic session management
BranchAndroid.getInstance ().SetLifeCycleHandlerCallback (this, this);
```

This is the exception:
![screen shot 2016-03-09 at 13 07 38](https://cloud.githubusercontent.com/assets/9530975/13641645/fe445ba6-e5f7-11e5-8a3e-eb8563a5a72b.png)

**Comment by antonargunov** [comment]
Hello maqui01!
Thanks for report, we will fix that asap.

**Comment by antonargunov** [comment]
Hello maqui01!
Update please Branch nuget package and
use **BranchAndroid.Debug = true;**
instead of **BranchAndroid.GetInstance().Debug = true;**

**Comment by maqui01** [comment]
Thanks, now it's working but I'm having issues having the installs notified as branche's one :disappointed: 
You may close this issue.
PS: For the installs referrers Do I have to add a custom INSTALL_REFERRER receiver? I've already have analytics on my manifest. I've seen this on the native Android guideline, but failed to see it in Xamarins.

**Comment by antonargunov** [comment]
@maqui01 we are solving the same issue, next week we will deliver new version of Xamarin SDK.

**Comment by antonargunov** [comment]
@maqui01 We have uploaded new version of Branch SDK and changed documentation. New version based on minded native libraries we use for iOS/Android.

Can you send me link to description of custom install referrer for native Android?

**Comment by maqui01** [comment]
@antonargunov Sorry for not answering before! It's now working properly :smile:. 

I have other non-related issue, on Android once I installed the app in the phone It's not showing the 'download' button on the banner, I have to open the app pressing 'Download' and only then it changes the banner to 'download'. If they download the app from the playstore directly and open it, is it not enough to change the banner button text?
Thanks in advance.
PS: You may close this issue!

**Comment by maqui01** [comment]
Hi, it keeps writing this into console:
[BranchSDK] Branch is not initialized, cannot close session
Does it have something to do with not appearing the 'Open' button?

**Comment by antonargunov** [comment]
Hi @maqui01 sorry for delay, we have committed new version of Xamarin SDK with updated native libs. Try new version please.

**Comment by antonargunov** [comment]
@maqui01 we have uploaded new package to nuget.org

**Comment by maqui01** [comment]
Great I'll check that out!!

**Comment by maqui01** [comment]
So solved this issue, srry for not closing it.
