### ISSUE TITLE
2.1.6 Nuget package build issue

### ISSUE THREAD

**Issue by Sudarshanshetty** [BranchMetrics/xamarin-branch-deep-linking#33]
Hi,

   I am getting below error in xamarin iOS project. Can you please help me to solve it 

Error MT2002: Failed to resolve "System.Void ObjCRuntime.DelegateProxyAttribute::.ctor(System.Type)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" (MT2002) 

I have added 2.1.6 branch io nuget package.

When i add below piece of code in appdelegate class. i get the above error

 BranchIOS.Init("key_test_ebkY2JyMRCUqeEdJ5KfaSbcoAzdcxfMn", options, this);  

Regards,
Sudarshan Shetty

**Comment by antonargunov** [comment]
Hello @Sudarshanshetty,
does "this" implement IBranchSessionInterface or IBranchBUOSessionInterface?

**Comment by Sudarshanshetty** [comment]
ya we have implemented . Please find below snippet
    public partial class AppDelegate : UIApplicationDelegate,IBranchSessionInterface

 #region IBranchSessionInterface implementation

        public void InitSessionComplete(Dictionary<string, object> data)
        {
            // Do something with the referring link data...
        }

        public void SessionRequestError(BranchError error)
        {
            // Handle the error case here
        }

        #endregion

**Comment by antonargunov** [comment]
@Sudarshanshetty try to set "linker behaviour" to "don't link"

**Comment by Sudarshanshetty** [comment]
@antonargunov : But it will effect my other library . Can you please tell why we need to set "linker behaviour" to "don't link"

**Comment by antonargunov** [comment]
http://xamarin21.rssing.com/browser.php?indx=23562832&item=23109
We can update the package, but I can't guarantee that new package will help you.

Can you try to put our SDK source code into your project?

**Comment by Sudarshanshetty** [comment]
So latest nuget package you have updated is built with Xamarin beta SDK ?

We tried with updating nuget packages in some other project  , we are getting same issue in all projects .

**Comment by antonargunov** [comment]
@Sudarshanshetty all our package versions were built with stable Xamarin versions, we don't use Xamarin beta versions.

>>We tried with updating nuget packages in some other project , we are getting same issue in all projects.

Can you explain that?
What packages did you try?
What is your version of Xamarin?

Also, can you download our Xamarin SDK and try to run our iOS testbed?

**Comment by Sudarshanshetty** [comment]
Can you explain that?
1We have already implemented branch.io in of old project. it was working very good. we just took update by clicking on update in xamarin studio, it got updated to 2.1.6 version. Also we tried in the new project in which we are trying to integrate branch.io for the first time . that also got failed.

What packages did you try?
https://www.nuget.org/packages/Branch-Xamarin-Linking-SDK/     version number 2.1.6

What is your version of Xamarin?
5.10.1 (build 6) , iOS SDK 9.1

**Comment by venky284** [comment]
@antonargunov , any updates on this issue?
We face the same issue mentioned here in our apps.
When linker behaviour is set as not to link, the integration works and branch links opens the app.
But we do have other libraries in the project, which needs to be linked. So any estimated time for this fix?

**Comment by antonargunov** [comment]
Hi @venky284 , sorry but I can't reproduce that.
Can you provide me with info:
- what library(s) do you have in your project?
- if you use PCL, what PCL profile do you use?
- if you don't use PCL - write "no" please

And then I will create new project and will try to reproduce that issue.

**Comment by antonargunov** [comment]
Hi @venky284 , did you try other linker behaviours? If yes, what is result?

**Comment by antonargunov** [comment]
@Sudarshanshetty you wrote "We have already implemented branch.io in of old project", what version does work nice for you?

**Comment by venky284** [comment]
@antonargunov 
We have other libraries for barcode scanners and loading the images.
PCL, we use targeting .Net 4.5
We are facing the issue in iOS (Xamarin)

**Comment by venky284** [comment]
@antonargunov , at the moment we use 2.1.3, which used to work before the 2.1.6 release.
Now the apps are doesn't open up with the bnc.lt links, where in it redirects to appstore and tapping open from there, opens the app. This is expected as we are using a legacy version. 

But to update the sdk to 2.1.6, we face the above mentioned issue. Hoping for an early resolution.

**Comment by antonargunov** [comment]
@venky284 update will be soon
Note: in new version of SDK we will remove non-BranchUniversalObject functional

**Comment by venky284** [comment]
@antonargunov , could we get any ETA on the updated SDK?

**Comment by venky284** [comment]
@antonargunov  , could we get any ETA on the updated SDK?

**Comment by antonargunov** [comment]
@venky284 Hi, sorry, for delay.
We are going to publish new version this week.

**Comment by antonargunov** [comment]
We have uploaded new version of Xamarin SDK.
Read please documentation, because there are several changes in new SDK.
You can find samples for iOS and Android (form, non-form) in our repo.
Feel free to create new issue after integration of new version.
