### ISSUE TITLE
What new features / bugs are squashed when upgrading from 1.2 to 2.1 ?

### ISSUE THREAD

**Issue by makerofthings7** [BranchMetrics/xamarin-branch-deep-linking#34]
I'm using Branch in an app where all code needs to be in C#.  The thin wrapper will not pass code review, since that staff  only knows C# not Obj-C.

We will continue with 1.2 -locked, however I want to know more about the statement below (what feature, what bugs?

>  This fixed a ton of bugs and added additional functionality, but will require you to change the interfaces.

**Comment by antonargunov** [comment]
Hi @makerofthings7 , first version of Xamarin SDK is written like a one more project.
From version 2.0.0 we have been started using of native iOS and Android libs in Xamarin SDK (through binding). That means all changes and new features from native iOS and Android appear in Xamarin SDK automatically without additional development.

You can investigate new features, fixes, etc. in Android and iOS threads.
Each SDK has changelog.md, and you can see all changes.

Note: If you plan to use new version, you have to wait our newest Xamarin SDK that we are creating right now.

**Comment by antonargunov** [comment]
Hi @makerofthings7 - we have updated our Xamarin SDK to version 3.
