### ISSUE TITLE
Is Microsoft.Net.Http needed in nuspec

### ISSUE THREAD

**Issue by dhaligas** [BranchMetrics/xamarin-branch-deep-linking#45]
Is the dependency on Microsoft.Net.Http needed in nuspec?

Appears it is not used

**Comment by dhaligas** [comment]
@antonargunov is this needed?  this http pkg is 2 years old.

**Comment by antonargunov** [comment]
HI @dhaligas , I will check, that dependence remains from SDK v.1.
If we don;t need that, I will delete that dependence in the next nuget package.
Thanks for asking!

**Comment by dhaligas** [comment]
@antonargunov any updates on this?

**Comment by antonargunov** [comment]
@dhaligas, http is not needed.
I deleted that dependence in new version.
We will submit new version tomorrow.
