### ISSUE TITLE
App link does not pass parameters when choosing app instead of chrome

### ISSUE THREAD

**Issue by HectorMeneses333** [BranchMetrics/xamarin-branch-deep-linking#52]
I have the following behavior:
- Install app
- In android phone, click on app link : HTTPS://homescout.app.link/bubbles/?l=123456
- I'm asked if I would like to use com.hbm2.homescout or chrome to open the link 
- If I choose com.hbm2.homescout, I don't get any session parameters in the app.
- If I choose chrome, then chrome asks me if I would like to open the link with com.hbm2.homescout, I say yes and then I can see session parameters in the app.

What am I doing wrong? 

Thanks!
Hector

**Comment by antonargunov** [comment]
Hi @HectorMeneses333 ,
It looks like you have an issue in your configuration of Branch.
Please send e-mail to our integration team, they will help you.
