### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by petersondrew** [BranchMetrics/xamarin-branch-deep-linking#55]
The documentation [here](https://dev.branch.io/getting-started/integration-testing/guide/xamarin/#xamarin-forms-projects) shows that the way to initialize a xamarin forms application is something like this:
```csharp
public class App : Application, IBranchSessionInterface
{
    protected override void OnResume ()
    {
        Branch branch = Branch.GetInstance ();
        Branch.Debug = true;
        branch.InitSessionAsync (this);
    }
}
```

However, this repository shows that for xamarin forms projects we should set up the branch session in AppDelegate/MainActivity. Which is the correct way? It seems like the key differences are related to having to manually specify the branch key (instead of it being read form plist/resource), and not passing the launch options on iOS. Does the `OnResume` method properly retrieve the launch options, which I'm assuming is necessary for deferred deeplinking to work properly?

The reason I felt this was an issue, instead of just a customer service email, is that the documentation here conflicts with what is on the main documentation site.

**Comment by antonargunov** [comment]
Hi @petersondrew , sorry, I don't know why we have old version of documentation on the site.
I will ask your team to update the documentation.

Read please documentation from Xamarin repository:
https://github.com/BranchMetrics/xamarin-branch-deep-linking#1---introduction
