### ISSUE TITLE
Links generated from Droid app are not setting canonical id

### ISSUE THREAD

**Issue by petersondrew** [BranchMetrics/xamarin-branch-deep-linking#57]
We're noticing that when using the xamarin sdk, when generating branch links from shared code
```csharp
var link = new BranchUniversalObject
{
    canonicalIdentifier = someGuid.ToString(),
    contentDescription = someDescription,
    type = "Thingy"
};
```
The canoncial_id is properly set when generated by iOS, but for some reason canonical_url is being filled with that value when generated on Droid. We've verified this by inspecting the liveview in our branch dashboard. The canonical_id is not set, and the url is, even though none of our code attempts to do so (and the same code runs on our end, regardless of platform).

This seems like a bug with either the Droid SDK or the Branch API that it is calling. Any thoughts on this?

**Comment by antonargunov** [comment]
Hi @petersondrew , let me check.

**Comment by petersondrew** [comment]
It appears that it was resolved with this commit https://github.com/BranchMetrics/xamarin-branch-deep-linking/commit/7b2b3f417e3ad611578106fcb3a2cc81fd6c6873#diff-57821b5282021cec21075265937b79ed 

We updated to the latest nuget package and that resolved it. Thank you.
