### ISSUE TITLE
Branch Android not hitting InitSessionsComplete

### ISSUE THREAD

**Issue by rikkieb34** [BranchMetrics/xamarin-branch-deep-linking#64]
I am having an issue where I call the Branch.Init() in the Branch Package version 3.0.13.  I am doing a simple call to the Branch.Init() with my live branchkey and am not receiving a response from branch in the InitSessionsComplete().  I am able to go to a previous commit and access the information that I need.  

Here is my Init() code:

void BranchInit()
{
        var branchkey = myBranchKey;
        if (String.IsNullOrWhiteSpace(branchkey))
        {

        TraceLog.Error(TAG, "APP BUILT WITHOUT BRANCH API KEY");
        #if DEBUG
            throw new InvalidOperationException("No Branch Key set, check BuildInfo.xml");
        #else
            return;
        #endif
        }
    
        //TraceLog was here, confirmed that it got here
        BranchAndroid.Init(this, branchkey, this);
}

Any suggestions on how to resolve this?

**Comment by antonargunov** [comment]
Hi @rikkieb34 , sorry for delay,

Look at our example please:
https://github.com/BranchMetrics/xamarin-branch-deep-linking/blob/master/Branch-Xamarin-Testbed.Droid/TestBedApplication.cs

https://github.com/BranchMetrics/xamarin-branch-deep-linking/blob/master/Branch-Xamarin-Testbed.Droid/MainActivity.cs

You should add several info into android manifest from app class and in activity class.

**Comment by AntRemo** [comment]
@rikkieb34 @antonargunov 

I just upgraded to 3.0.14 from 2.1.4 (It's been a while) and I'm experiencing the same issue on Android. iOS works for me.

Oddly the build deployed from VS works, but the build from automated build (with the same build configuration) does not.

**Comment by rikkieb34** [comment]
@AntRemo @antonargunov 

Sorry its been a while since I posted anything on this, but I am having the same issue as AntRemo.  My Visual Studio debug build works great, however, when I try to use my automated building system it fails.  I added some traces to see if I can spot where it fails, but it only hits my trace to initialize branch.  My traces in InitSessionsComplete() and SessionRequestError() are not getting hit.  Have you had any success with the latest version (3.0.15).

**Comment by antonargunov** [comment]
@rikkieb34 try new version please

**Comment by rikkieb34** [comment]
@antonargunov I am using the latest version.  I have tried setting the launchmode to be single task, I have tried using the intentfilters per the examples given without any success.  Do I need to use the getautoinstance()?  What is the function used for?  I, currently, have the correct branch key and I am able to get the build to work properly in debug builds, however release builds are not working appropriately.  Are there any other suggestions that you could think of that would help?

**Comment by antonargunov** [comment]
@rikkieb34 , yes you need to use getautoinstance(), this function is for correct initialization of Branch at the start of the app. Also, as you can see, you need to add into metadata your branch key.

**Comment by rikkieb34** [comment]
@antonargunov There are multiple branchkeys that are used between the apps that I am building.  Is there a way to use the getautoinstance() in a way that would allow me to use my dynamic branchkeys that are created for my apps.

**Comment by rikkieb34** [comment]
@antonargunov I ended up getting it to work thank you for your help.

**Comment by antonargunov** [comment]
@rikkieb34 , in our example we use 
`[MetaData("io.branch.sdk.BranchKey", Value = "@string/branch_key")]`

you can add into strings.xml several keys (branch_key01, branch_key02, etc.) and switch they as you wish, but you need to use the same key in the method
`BranchAndroid.Init (this, GetString(Resource.String.branch_key), appBUO);`

**Comment by rikkieb34** [comment]
@antonargunov I achieved what I needed when calling getautoinstance(this.ApplicationContext) without any MetaData.  Can this cause any issues?  Currently, it seems to be working correctly.

**Comment by antonargunov** [comment]
@rikkieb34 check received parameters for clicked link

**Comment by antonargunov** [comment]
I hope all is nice
