### ISSUE TITLE
AppIcons for iOS not displaying

### ISSUE THREAD

**Issue by saamerm** [BranchMetrics/xamarin-branch-deep-linking#71]
Hi 
I wasn't able to implement the Android version of the app when I tried to import all the necessary files, so I decided to build my project around the example and change the code from there. (Terrible idea)

I completed coding it completely and the last part which is supposed to be the easiest, is to change the app icons. I found out that the existing iOS App Icons are set properly but don't work -.-
Please let me know how I can make the default images work as app icons, so I can implement it in my project as well.
Thank you

**Comment by saamerm** [comment]
Has anyone been able to figure out how to make the App Icons work for the Xamarin Forms example?

**Comment by antonargunov** [comment]
HI, try to read xamarin docs.

https://developer.xamarin.com/guides/ios/application_fundamentals/working_with_images/app-icons/#managing

https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/publishing_an_application/part_1_-_preparing_an_application_for_release/#Specify_the_Application_Icon

**Comment by saamerm** [comment]
I figured it out! 
I had tried everything that I used while making other apps.
Somehow this worked, you have to delete the icon set and then import an existing one that is made in another solution. If anyone needs help, they can contact me.
