### ISSUE TITLE
Update of branch io sdk for Xamarin-IOS error

### ISSUE THREAD

**Issue by softsan** [BranchMetrics/xamarin-branch-deep-linking#77]
We tried to update your nuget package of Branchio sdk link for Xamarin. Its build up fine on android, but on iOS it shows following compile time error:

Error MT2101: Can't resolve the reference 'BranchUniversalObject', referenced from the method 'System.Void AgriSync.App::InitSessionComplete(BranchUniversalObject,BranchLinkProperties)'

nuget version: https://www.nuget.org/packages/Branch-Xamarin-Linking-SDK
Branch-Xamarin-Linking-SDK -Version 4.0.3

So any thought on how to solve this?

**Comment by antonargunov** [comment]
@softsan , which version did you use before updating?

**Comment by softsan** [comment]
3.0.18

**Comment by antonargunov** [comment]
please update xamarin sdk
