### ISSUE TITLE
cannot debug in Simulator for xamarin.iOS

### ISSUE THREAD

**Issue by TingtingAn** [BranchMetrics/xamarin-branch-deep-linking#78]
I am using the sdk for xamarin.iOS project.  But i cannot debug the project after installed our sdk for ios Simulator.  It works for iphone device.
Here is the error message:

```
linking failed, undefined symbol: _BRANCH_REQUEST_KEY_UPDATE. This symbol was referenced by the managed member IOSNativeBranch.Constants.BRANCH_REQUEST_KEY_UPDATE. 
Please verify that all the necessary frameworks have been referenced and native libraries linked.		
```

**Comment by antonargunov** [comment]
@TingtingAn , try to set linker behaviour with "Framework SDK's only"

**Comment by TingtingAn** [comment]
@antonargunov   after changing to "Link Framework SDKs only",  it works.   Thank you very much!
