### ISSUE TITLE
Branch deep linking SDK for Xamarin in iOS does not work

### ISSUE THREAD

**Issue by jorgemht** [BranchMetrics/xamarin-branch-deep-linking#83]
I followed the same steps, and in android it works. In 10 minutes it had worked. But on iOS it is unable to open my application through a url. Android is very quick to configure and operate.

In my real project my version in Xamarin Forms is 2.5.0.280555 and the version of Branch-Xamarin-Linking-SDK is 4.0.5. It has been working (in android and iOS) until last month when on the 25th I had to accept the new terms and conditions. Two weeks ago I try change my Default Link Domain, change OldName.app.link for NewName.app.link. I change the url in android and IOS, in android works in iOS still does not work on iOS despite changing the domain ( I did not know what else to do )

In my dashboard in IOS I check I have an iOS APP and Enable Universal Links, I add the Bundle Identifiers and my Apple App Prefix. My Bundle Identifiers in Apple Developer is in lowercase
as in my project and in the dashboard. 

I. Create an Apple device Provisioning Profile for the app **yes**
II. Enter the app's settings on the Branch dashboard **yes**
III. Configure the Xamarin project's Info.plist file **yes**
IV. Configure the Xamarin project's Associated Domains entitlement  **yes**
V. Add Branch calls to the AppDelegate.cs file => **The same code**

I have created a project in Xamarin forms, in android works on iOS not using Xamarin Forms 3.1. So, I do not know what happen.

I test my url in http://branch.io/resources/aasa-validator and the result is =>  This domain validates, JSON format is valid, and the Bundle and Apple App Prefixes match (if provided).
Below you’ll find a list of tests that were run and a copy of your apple-app-site-association file:

**Comment by antonargunov** [comment]
@jorgemht please, send this information to integrations@branch.io
