### ISSUE TITLE
Wrong method name in documentation

### ISSUE THREAD

**Issue by monirul-hemal** [BranchMetrics/xamarin-branch-deep-linking#84]
I am trying to use the following method

Branch.GetInstance().GetLatestReferringParams()

to get the current session parameters. But I can't find any method named "GetLatestReferringParams". I am using the latest package from nuget(4.0.5).

Is GetLastReferringParams does the same as GetLatestReferringParams?

**Comment by antonargunov** [comment]
@monirul-hemal yes, GetLastReferringParams is the same as GetLatestReferringParams, sorry for wrong naming.
