### ISSUE TITLE
"+clicked_branch_link" property in BranchUniversalObject is different on Android and iOS

### ISSUE THREAD

**Issue by kwacks** [BranchMetrics/xamarin-branch-deep-linking#88]
in a Xamarin forms project, the property retrieved from +clicked_branch_link in BranchUniversalObject is different:

- iOS: value is returned as 0/1

- Android value is returned as true/false

This means we have to do special parsing in the forms project. 
 The data should be normalized shouldn't it?

Using latest Xamarin forms and Branch SDK 4.08

**Comment by antonargunov** [comment]
@kwacks i will this in the next version, thanks for report
