### ISSUE TITLE
'Branch-Xamarin-Linking-SDK 5.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

### ISSUE THREAD

**Issue by sirfarmalot** [BranchMetrics/xamarin-branch-deep-linking#90]
I get this error when trying to build an Xamarin Forms project with the latest Branch SDK.
I am using the latest version (3.4) of Xamarin Forms 

_warning NU1701: Package 'Branch-Xamarin-Linking-SDK 5.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project._

Can Branch SDK be integrated successfully with the latest Xamarin Forms?

**Comment by antonargunov** [comment]
@sirfarmalot
yes,
and i am going to change target framework in the next version, sorry fo that

**Comment by sirfarmalot** [comment]
How can I temporarily fix this and move on with Branch Integration instead of choosing another deep link/attribution provider?

**Comment by antonargunov** [comment]
@sirfarmalot tomorrow I will upload new version, wait please

**Comment by antonargunov** [comment]
@sirfarmalot our SDK was created like PCL library; unfortunately I did not find a way how to solve your request fast; to support .netstandard 2.0 we need to develop  SDK like .net standard library. I will work with that tasks next weeks. Right now, you can just use our SDK 5.0.1, all will works nice.

**Comment by sirfarmalot** [comment]
Thank you for the response and info.

> _Right now, you can just use our SDK 5.0.1, all will works nice_


what does that ^ mean, exactly what I thought I did....?

I followed these instructions and chose the 5.0.1 version on nuget instead of 3.0....

> To add the Branch NuGet package to a project:
> 
> Right-click on each project and select Add > Add NuGet Packages
> If not already present, find the Microsoft BCL Build Components package version 1.0.21 and add it to the project
> Find the Branch Xamarin SDK package version 3.0 and add it to the project

pls point me in the direction of this package, either on nuget or the github repo
thank you.

**Comment by antonargunov** [comment]
@sirfarmalot 
> I followed these instructions and chose the 5.0.1 version on nuget

right, use 5.0.1 version, this is last actual version

**Comment by sirfarmalot** [comment]
@antonargunov  You keep saying to use that version but, this whole issue is behind using that exact version.
Every time I use that version in the project the error posted in the title of this issue arises.

Please just say/admit to all other developers coming across the same issue and reading this thread,  **there is no immediate way to use _Branch.io Xamarin 5.0.1 SDK with the latest Xamarin Forms 3.0.+_**

**Comment by antonargunov** [comment]
@sirfarmalot this is not an error, this is a warning.
Your app should compile even with this warning.

**Comment by sirfarmalot** [comment]
ahhh, Ty for the clarification.
I missed that, there must be something else stop the project from compiling....
 
I've since moved on to _AppsFlyer_. 
But I will try Branch SDK in another Xamarin Project.
And report my results here. 

ty again.
