### ISSUE TITLE
Purchase events not tracking on iOS with X.Forms

### ISSUE THREAD

**Issue by joaosilvareed** [BranchMetrics/xamarin-branch-deep-linking#97]
Hi,

I'm using Xamarin Forms and the method Branch.GetInstance().SendEvent(ev); doesn't seem to be working on iOS.
I can't see any purchases on our reports.
Exactly the same code works perfectly on Android.

Thanks.

Regards,

**Comment by antonargunov** [comment]
@joaosilvareed 
look at my screenshot that I made from my dashboard:
https://www.dropbox.com/s/i98osya8uvocvxy/Screenshot%202019-02-17%2018.56.11.png?dl=0

can you add in your app a button which will send your event to don't wait any purchase action and then tap button and check dashboard? you can do this with another account if you don't want to spam you real account.

**Comment by joaosilvareed** [comment]
I might have found the problem, Branch Universal Objects for some reason on iOS only work if expirationDate is set. Android works fines without setting it...

**Comment by antonargunov** [comment]
@joaosilvareed thanks for report, let me check and ask our ios team about that

**Comment by antonargunov** [comment]
@joaosilvareed I added default expiration date for BUO to avoid issue with ios platform

**Comment by antonargunov** [comment]
@joaosilvareed new version of SDK is available
