### ISSUE TITLE
Extracting data embedded via HTTP API

### ISSUE THREAD

**Issue by petemillermultimedia** [BranchMetrics/xamarin-branch-deep-linking#98]
I'm embedding custom data into my link via https://api2.branch.io/v1/url with 3 parameters
"branch_key" : MY_BRANCHIO_KEY,
"data" : { "registrationcode" : "012345678" },
"$canonical_identifier", "content/123"

When I call BranchUniversalObject.metadata.GetCustomData() I expected to find "registrationcode" as an entry, but I don't. I also tried this with appending additional parameters to the end of the link; those parameters appear in the custom data, but the registrationcode item is unavailable. How do you extract data embedded in the link?

**Comment by antonargunov** [comment]
@petemillermultimedia let me check

**Comment by petemillermultimedia** [comment]
I forgot to mention, I'm using the Xamarin NuGet package for the SDK. I'm aware that there are differences with the native SDKs.

**Comment by petemillermultimedia** [comment]
I figured it out by examining the Xamarin SDK code. The proper format should be (I put $canonical_identifier in the wrong place):

"branch_key" : MY_BRANCHIO_KEY,
"data" : { "$canonical_identifier", "content/123",
              "metadata" : {"registrationcode" : "012345678" }}

I took instructions for using the API from https://docs.branch.io/apps/deep-linking-api/#link-create
Apparently there is a major undocumented difference between the way the Xamarin SDK and native SDKs receive custom data.

**Comment by antonargunov** [comment]
@petemillermultimedia thanks for investigation and report; I checked and received the same result, I sent a request to our team about wrong documentation.

**Comment by antonargunov** [comment]
@petemillermultimedia we updated the documentation, also we fix the issue with differences in format of metadata on android and ios

**Comment by antonargunov** [comment]
@petemillermultimedia new version of SDK is available
